PP-8736 - Create deploy GH action
Axcient/ax-api-docs pull request #1
Opened 2024-05-16 18:13 UTC by lucas-av7

# Changes

Create the deploy GH action for main, staging and production

# Notes

Ticket: https://jira.slc.efscloud.net/browse/PP-8736

2024-05-20 14:03 UTC, axbgrossi commented on .github/workflows/deploy.yml
> +          aws s3 cp ./index.html s3://$S3_BUCKET/ --only-show-errors
```suggestion
          echo "Deploying index.html to s3://$S3_BUCKET/"
          aws s3 cp ./index.html s3://$S3_BUCKET/ --only-show-errors
          echo "S3 deployment complete."
```

2024-05-20 14:05 UTC, axbgrossi commented on .github/workflows/deploy.yml
> +          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $SOURCE_PATH --region $AWS_REGION
```suggestion
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $SOURCE_PATH --region $AWS_REGION
          echo "CloudFront cache invalidation complete."
```

2024-05-20 14:07 UTC, axbgrossi commented on .github/workflows/deploy.yml
> +          fi
```suggestion
          fi
          echo "Environment setup complete."
```

2024-05-20 14:30 UTC, axbgrossi requested changes

2024-05-20 14:30 UTC, axbgrossi commented on .github/workflows/deploy.yml
> +          echo "CloudFront cache invalidation complete."
```suggestion
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $SOURCE_PATH --region $AWS_REGION &&\
          echo "CloudFront cache invalidation complete." ||\
          echo "CloudFront cache invalidation failed."
```

2024-05-20 15:57 UTC, merged

2024-05-21 11:38 UTC, sam-axcient reviewed
LGTM

2024-05-21 11:38 UTC, sam-axcient commented on .github/workflows/deploy.yml
> +          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $SOURCE_PATH --region $AWS_REGION
```suggestion
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths $SOURCE_PATH
```
specifying a region is redundant as they are already set by `Configuring AWS credentials` step